spring.application.name=GeneradorHorarios

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/horario
spring.datasource.username=postgres
spring.datasource.password=2412

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true